### ISSUE TITLE
Struggling to get custom-ui to work

### ISSUE THREAD

**Issue by nickdos** [Mariusthvdb/custom-ui#108]
I've installed via HACS and can see it is loaded via /info page:

![image](https://github.com/Mariusthvdb/custom-ui/assets/532845/84b8e6ee-94b2-4489-8451-bebbc92c47cd)

I've got a `customise.yaml` file configured from `configuration.yaml` as

```yaml
homeassistant:
  customize: !include customize.yaml
```

In `customize.yaml` I've got:

```yaml
sensor.easyweather_uv_index:
  templates:
    icon_color: >
      if this.state|int(default=0) > 0 return 'red';
      if this.state == '5' return 'green';
      if this.state == '6' return 'orange';
      if this.state == '7' return 'red';
      return blue;
```

I've done a full restart of HA after changes.

In developer tools I can see the entity as:

![image](https://github.com/Mariusthvdb/custom-ui/assets/532845/f9e3e123-56fe-4cd0-a2d1-81437a5a08ac)

In my Lovelace UI the entity does not show any colour in either a entities list or glances card:

![image](https://github.com/Mariusthvdb/custom-ui/assets/532845/db8b1b74-0b20-4fcb-8e45-1a6393cdcdcb)
![image](https://github.com/Mariusthvdb/custom-ui/assets/532845/3d5ef267-4cc7-43fe-a4c2-87725fc45b88)

Am I missing some last step?

**Comment by Mariusthvdb** [comment]
dont use `this.state` but `state` in the templates

**Comment by nickdos** [comment]
Thanks for clarifying. Ah yes, a newbie mistake. 

I did take all the code from the examples page but failed to appreciate there were differences between the way it is called depending on the context. I now see I went straight for the first example code I found in the examples page and failed to recognise the syntax was different to the bits further down.

I'm now not able to get the resources to reload. I can't find a "Reload resources" option in the Lovelace 3 dots menu (only has "edit dashboard" and if in edit mode only shows 4 options, none of what are "reload resources"). When I try to call the service: "lovelace.reload_resources" it does nothing and I see JS errors in the console counting up with every click of the button (Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this.hass.services[a][s]')). It also does not autocomplete the Lovelace service name, as it does for other services. When I try the YAML mode in Services I see a different JS error: Failed to load resource: the server responded with a status of 404(). Has this changed in a recent HA update? 

The only way I was eventually able to reload it was going into the "Manage Resources" section of the UI and clicking on the custom-ui entry and then selecting the "update" button.

**Comment by Mariusthvdb** [comment]
not seeing the 3-dots menu items is no custom-ui interference, they are not touched.
probably card_mod, or maybe kiosk-mode?

you seem to have more generic resource trouble, maybe take that to the community or create an issue tracker in the core / frontend repo if you can provide more useful loggings.

fwiw, reload resources is available with custom-ui in all the places it should be, and I believe we can close this here?

**Comment by nickdos** [comment]
I believe that `lovelace.reload_resources` is only active when using **YAML mode** for Lovelace configuration. If using the UI configuration, then it is not available. Similarly the "reload resources" option in the UI is NOT PROVIDED when using UI mode.

I think you should update your documentation to reflect the differences in using YAML vs UI mode for Lovelace settings. Most newer users will be using UI mode as that is the default setting.
