### ISSUE TITLE
Uncaught error from Edge 117.0.2045.60 on Windows 10 ReferenceError: Polymer is not defined /hacsfiles/fan-control-entity-row/fan-control-entity-row.js:9:28

### ISSUE THREAD

**Issue by danielbrunt57** [Mariusthvdb/custom-ui#109]
Hey Marius,
Have you run across this before:
```
Logger: frontend.js.latest.202310050
Source: components/system_log/__init__.py:300
First occurred: 7:42:07 PM (10 occurrences)
Last logged: 8:49:38 PM

Uncaught error from Edge 117.0.2045.60 on Windows 10 ReferenceError: Polymer is not defined /hacsfiles/fan-control-entity-row/fan-control-entity-row.js:9:28
Uncaught error from Edge 117.0.2045.60 on Windows 10 ReferenceError: Polymer is not defined /hacsfiles/light-entity-row/light-entity-row.js:10:40
Uncaught error from Edge 117.0.2045.60 on Windows 10 TypeError: Cannot read properties of null (reading 'shadowRoot') updateMoreInfo (/hacsfiles/custom-ui/custom-ui.js:53:7) dispatchEvent (src/common/dom/fire_event.ts:76:7) nextRender (src/components/ha-expansion-panel.ts:131:14)
```
I've uninstalled fan-control-entity-row and light-entity-row in HACS and cleared my MS Edge browser cache but the error persists.
I am perplexed as to what/where is causing it!

Thanks,
Daniel

**Comment by Mariusthvdb** [comment]
Yes, the polymer warning is related to the HA move away from polymer.

This however is unrelated to custom Ui and you should take it to the respective repos.

They should probably update to the  current implementation without Polymer

**Comment by danielbrunt57** [comment]
After several restarts, the light-entity-row error disappeared so I went searching the file system and found fan-control-entity-row still in /.storage/lovelace_resources and .storage/hacs.repositories.  I removed the entries, restarted and the error is now gone.
