### ISSUE TITLE
release '20231123' is broken on HACS

### ISSUE THREAD

**Issue by hatemzidi-pro** [Mariusthvdb/custom-ui#115]
I just updated the '20231123' release under HACS and I got a 404.
After investigation, HACS still calls custom-ui under its old path `http://../hacs/custom-ui/custom-ui.js` and it's not using the new filename `custom-ui-icon-color.js`

**Comment by Mariusthvdb** [comment]
thanks for notifying me.
it is probably caused by me have several resources under the same link, sorry for that.

I should reorganize.

For the time being, are you good in downgrading to the release before?

they are fundamentally different as I tried to document in the release notes.

**Comment by Mariusthvdb** [comment]
I split up the repos, so the issue should no longer turn op
