### ISSUE TITLE
Is it just my system or does custom-ui prevent yaml reloading via Location & Customizations?

### ISSUE THREAD

**Issue by danielbrunt57** [Mariusthvdb/custom-ui#141]
Hi Marius,
Here's my current issue: If I add/delete/change anything in `customize:`, the quick **YAML configuarion reloading** of `LOCATION & CUSTOMIZATIONS` in Dev Tools does not reflect my change  I have to restart Home Assistant to implement the edit(s).  Is this normal behaviour with custom-ui installed or do I have a bug somewhere in my customizations?

**Comment by Mariusthvdb** [comment]
without any example, I couldnt say....


usually the changes only kick in after a state change. you can force that in dev tools state

**Comment by danielbrunt57** [comment]
I tried setting a new state on an entity after saving a change in configuration.yaml and reloading location & customization but the new value for the templated attribute did not update.  Here's my code currently:
```
homeassistant:
#  customize: !include customize.yaml
#  customize_domain:
#    light:
#      templates:
#        icon_color: "return state === 'on' ? 'yellow' : 'grey';"
  customize_glob:
#    "*.*":
#      hide_attributes:
#        - templates
    sensor.*_battery_plus:
      new_attribute: "and again"
      templates:
        templated_attribute: "Just a string"
        battery_last_replaced_button: return 'button.' + entity.entity_id.split('.')[1].split('_battery_plus')[0] + '_battery_replaced';
        icon_color: >
          var r = Math.min(255, Math.round(510 - 5.10 * ~~Number(state)));
          var g = Math.min(255, Math.round(5.10 * ~~Number(state)));
          var h = r * 0x10000 + g * 0x100;
          return '#' + ('000000' + h.toString(16)).slice(-6);
#    binary_sensor.*_motion:
#      templates: &motion_templates
#        icon: "return state === 'on' ? 'mdi:motion-sensor' : 'mdi:human-male';"
#        icon_color: "return state === 'on' ? 'yellow' : 'grey';"
#    binary_sensor.*_occupancy:
#      templates: *motion_templates
#    sensor.*_battery:
#      templates: &battery_color
#        icon_color: >
#          var r = Math.min(255, Math.round(510 - 5.10 * Number(state)));
#          var g = Math.min(255, Math.round(5.10 * Number(state)));
#          var h = r * 0x10000 + g * 0x100;
#          return '#' + ('000000' + h.toString(16)).slice(-6);
#    sensor.*_battery_level:
#      templates: *battery_color
#        icon_color: >
#          var r = Math.min(255, Math.round(510 - 5.10 * Number(state)));
#          var g = Math.min(255, Math.round(5.10 * Number(state)));
#          var h = r * 0x10000 + g * 0x100;
#          return '#' + ('000000' + h.toString(16)).slice(-6);
```
![image](https://github.com/Mariusthvdb/custom-ui/assets/49846893/8cbdd2a3-7a36-4c43-bfdc-8065bbd1fff8)

Just before the above, I also removed custom-ui-only v2024.1.16 which I had manually installed, and installed custom-ui v2024.1.18 via HACS.

The other thing I'm wondering is whether I should be able to reference the templated attributes in Dev Tools?  Currently, I cannot.  the state_attr() returns `None `after a restart.  No, wait a second, now it's showing.  But it doesn't update in dev tools, template....

![image](https://github.com/Mariusthvdb/custom-ui/assets/49846893/ec10c24a-9524-45a0-80b4-bdd25e676d9f)
```
{% set entity = "sensor.bathroom_battery_plus" %}
{{ entity|replace("sensor.","button.")|replace("_battery_plus","_battery_replaced") }}
{{ state_attr(entity, 'new_attribute') }}
{{ state_attr(entity, 'icon_color') }}
{{ state_attr(entity, 'battery_last_replaced_button') }}
```
![image](https://github.com/Mariusthvdb/custom-ui/assets/49846893/e295d768-b849-4b4b-b0cc-a7442450686f)

This is what i see in dev tools template after a system restart:
![image](https://github.com/Mariusthvdb/custom-ui/assets/49846893/c0f8a75e-90e6-4931-b1cd-7a62069e01bd)

**Comment by danielbrunt57** [comment]
Those templated attributes still have not updated in dev tools>template...

**Comment by Mariusthvdb** [comment]
sorry, but you're not making this easy to assist.

please make a minimal failing example, so we can check that.

and no, the attributes can Not be templated n dev tools templates nor core backend templates. we tried, but there is no wa.

**Comment by danielbrunt57** [comment]
Ok, so upon deep reflection over the last 7 hours and reading and re-reading your documentation slowly and carefully, I came to realize that Dev Tools>Template couldn't possibly see or be influenced by the front-end templating which custom-ui overlays onto the state of things, I dropped that method of testing and went looking for a front-end view of things.  I used the battery-state-card where I could view attributes.whatever via its {KSting} within `name:` and `secondary_info:` and the custom templated attributes existed as I intended.  I changed to this simple config:
```
homeassistant:
  customize:
    sensor.bathroom_battery_plus:
      templates:
        battery_last_replaced_button: >
           ${ 'button.' + entity.entity_id.split('.')[1].split('_battery_plus')[0] + '_battery_replaced' }
#        icon_color: >
#          var r = Math.min(255, Math.round(510 - 5.10 * ~~Number(state)));
#          var g = Math.min(255, Math.round(5.10 * ~~Number(state)));
#          var h = r * 0x10000 + g * 0x100;
#          return '#' + ('000000' + h.toString(16)).slice(-6);
```
restarted HA and verified the state of that entity.  
I changed configuration.yaml to:
```
homeassistant:
  customize:
    sensor.bathroom_battery_plus:
      templates:
        battery_last_replaced_button: >
           ${ 'button.' + entity.entity_id.split('.')[1].split('_battery_plus')[0] + '_battery_replaced' }
        icon_color: >
          var r = Math.min(255, Math.round(510 - 5.10 * ~~Number(state)));
          var g = Math.min(255, Math.round(5.10 * ~~Number(state)));
          var h = r * 0x10000 + g * 0x100;
          return '#' + ('000000' + h.toString(16)).slice(-6);
```
and used reload Locations and customizations but dev tools>state did not show the new attribute.
I then changed the state using dev tools but still no change.
Then I reloaded the MQTT integration and the attributes updated.
I repeated the process, altering included/commented, redid the same steps and although the definition within the templates attribute updated, the resulting attribute was still present.
```
homeassistant:
  customize:
    sensor.bathroom_battery_plus:
      templates:
#        battery_last_replaced_button: >
#           ${ 'button.' + entity.entity_id.split('.')[1].split('_battery_plus')[0] + '_battery_replaced' }
        icon_color: >
          var r = Math.min(255, Math.round(510 - 5.10 * ~~Number(state)));
          var g = Math.min(255, Math.round(5.10 * ~~Number(state)));
          var h = r * 0x10000 + g * 0x100;
          return '#' + ('000000' + h.toString(16)).slice(-6);
```
![image](https://github.com/Mariusthvdb/custom-ui/assets/49846893/de5866fa-eb6b-4209-bec8-d90a11c3a807)

I now have a much better understanding of all the inner workings and although the last edit wasn't fully updated via reload, what I'm seeing appears to be just normal behaviour and I'm okay with that.  It's not like I'm doing edits all the time and since a full restart only takes about 90 seconds, it's not the end of the world.  Just a little inconvenient when changing things and troubleshooting my errors.

Thank you very much for your time looking at this!
