### ISSUE TITLE
Unexpected identifier 'state' in custom-ui template

### ISSUE THREAD

**Issue by JohannCR** [Mariusthvdb/custom-ui#144]
**Describe the bug**
Icon doesn't change. Maybe I configured it wrong ?
Thanks for any help

**Configuration in Yaml**
I load customize.yaml like so in the config :
```
homeassistant:
  customize: !include customize.yaml
```
Then in customize.yaml I have :
```
input_number.volet_petit_bureau:
  templates:
    icon: >
      if state === '100.0' return 'mdi:window-shutter-open';
      if state === '0.0' return 'mdi:window-shutter';
      return 'mdi:window-shutter-alert';
```

**Inspector Logs**
```
SyntaxError: Unexpected identifier 'state' in custom-ui template if state === '100.0' return 'mdi:window-shutter-open'; if state === '0.0' return 'mdi:window-shutter-alert'; return 'mdi:window-shutter';
```

**Expected behavior**
Icon should change depending on entity value.

**Comment by Mariusthvdb** [comment]
Please check the examples 
Hint: ()

**Comment by JohannCR** [comment]
My bad, needed to be in parenthesis like so
`state === '100.0'`

Works fine now ^^

**Comment by JohannCR** [comment]
> Please check the examples Hint: ()

Lol just figured this out and we commented at the same time^^
Thanks anyway !
