### ISSUE TITLE
Question: Device class use for styling

### ISSUE THREAD

**Issue by fn87** [Mariusthvdb/custom-ui#15]
I am looking in to the code and I can see device classes are something that shows up.

Can I style based on device class somehow?

**Comment by Mariusthvdb** [comment]
don't see any reason why not, device_class is an attribute, so customize on that.

works in regular Jinja:
```
{% if state_attr('binary_sensor.alerts','device_class') == 'problem' %} Problem
{% else %} No Problem
{% endif %}
```

depending on your styling wishes, you probably would be better off if you'd style on state, but, of course I dont know what you're after.
the main advantage of a device_class is the State, but of course the icon. So what would be left is the icon_color. Which would be best colored depending on state.
