### ISSUE TITLE
Operation not supported error

### ISSUE THREAD

**Issue by claudegel** [Mariusthvdb/custom-ui#16]
On HA 0.115.2 I get that error on reboot

Logger: frontend.js.latest.202009180
Source: components/system_log/__init__.py:193
First occurred: 21:33:58 (1 occurrences)
Last logged: 21:33:58
https://192.168.20.178:8123/local/community/custom-ui/custom-ui.js?v=20200528:940:0 NotSupportedError: Operation is not supported

**Comment by Mariusthvdb** [comment]
please update to the latest version in the repo, you are using an older version.

**Comment by claudegel** [comment]
My js file is at version 20200918.
My config is 
```
- url: /local/community/custom-ui/custom-ui.js?v=20200528
      type: module
```
should I change v=20200528 for v=20200918

**Comment by claudegel** [comment]
Still the same error: NotSupportedError: Operation is not supported
I'm on the latest 20200918

**Comment by Mariusthvdb** [comment]
cant see that here. please post the full config for custom-ui? how did you install it. Can you show the Info page, and right click inspector Console page, to see if it really is installed correctly

**Comment by claudegel** [comment]
Installed via hacs
info page say:  CustomUI: JS 20200918 adapted for HA 110.+
configuration.yaml:
```
frontend:
  extra_module_url:
    - /local/community/custom-ui/custom-ui.js
```
I also have a file customize.yaml loaded via 
```
homeassistant:
    customize: !include customize.yaml
```
where I have all my customisation

**Comment by Mariusthvdb** [comment]
Not using Hacs myself, but do you need the Frontend: setting if doing so? That is a replacement for the former way of installing. As documented in the readme

**Comment by claudegel** [comment]
I just removed the frontend setting en restart HA. Custom-ui is working and i'll see if this error come back.

**Comment by claudegel** [comment]
Error is gone. Thank you
