### ISSUE TITLE
Error during setup since 0.115.X+

### ISSUE THREAD

**Issue by Codename-11** [Mariusthvdb/custom-ui#18]
Hello, ever since 0.115 I've been getting this error. I assumed it was for everyone and due to the new updated but haven't seen any issues opened. Please advise if anyone can point me in the right direction. Thanks!

**HA Version:** Hassio Docker - 0.115.6
**Custom UI Version:** 20200918 adapted for HA110+ (Installed via HACS)
**Logger:** homeassistant.setup
**Source:** custom_components/customizer/__init__.py:63
**First occurred:** 12:33:57 AM (1 occurrences)
**Last logged:** 12:33:57 AM
Error during setup of component customizer

**Traceback (most recent call last):**
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/customizer/__init__.py", line 71, in async_setup
    add_extra_html_url('/local/custom_ui/state-card-custom-ui')
  File "/config/custom_components/customizer/__init__.py", line 63, in add_extra_html_url
    frontend.add_extra_html_url(
AttributeError: module 'homeassistant.components.frontend' has no attribute 'add_extra_html_url'

**Comment by dmerlani** [comment]
Hi, I have the same problem on 116 version. I have uploaded custom-ui.js but it seems HOME ASSISTANT is not loading it. In INFO i cannot find anything. Did someone succeed in importing custom-ui on the latest version?

**Comment by Mariusthvdb** [comment]
this is an error on customizer. That has been long deprecated. Please read the instructions carefully, and delete all previous install options.
