### ISSUE TITLE
Custom_UI 20200918 does not work with card_mod and HA 0.116.2

### ISSUE THREAD

**Issue by gadric** [Mariusthvdb/custom-ui#19]
Hi, 

I just upgraded to HA 0.116.2. Since this upgrade, my card-mod setting does not work any more, if custom-ui is activated. 

With card-mod, I am modifying the font size and space between 2 lines. This is the glance card, where I identified the problem. card-mod verison is 2.0.2

- type: glance
    show_icon: false
            columns: 6
            align: right
            style: |
              ha-card {
                font-size: 12px;
                margin-top: -2.5%;
              }
            state_color: true
            entities:
              - entity: sensor.hourly_current_total_power_consumption
                name: "Hourly"
              - entity: sensor.daily_current_total_power_consumption
                name: "Today"
              - entity: sensor.weekly_current_total_power_consumption
                name: "Weekly"
              - entity: sensor.monthly_current_total_power_consumption
                name: "Monthly"
              - entity: sensor.quarterly_current_total_power_consumption
                name: "Quarterly"
              - entity: sensor.yearly_current_total_power_consumption
                name: "Yearly"

**Comment by Mariusthvdb** [comment]
Maybe post on the card-mod GitHub, since that is not working ?

Can't say I see anything going astray here on all latest versions (card-mod was updated too)

**Comment by gadric** [comment]
Thank you for the quick reply. 

When I deactivate Custom UI, then it works as expected. So I am not sure if this is a card-mod issue only. However, I am opening a issue in the card-mod github too.

**Comment by Mariusthvdb** [comment]
ok, this is very interesting, yet the first time I hear another card doesn't work because of custom-ui. 

do you see any error messages?

As said, I use card-mod myself, and all is fine. So I am very interested in what Thomas would say what could be the conflicting thing here.
Please keep us informed?

**Comment by gadric** [comment]
In addition to the post in the card_mod repo, I have done more testing without Custom UI. So if I remove the Custom UI config in my configuration.yaml 

```yaml
frontend:
#   extra_module_url:
#     - /local/custom_ui/custom-ui.js
lovelace:
  mode: yaml
```

The result looks like this (which is correct). 

![Screenshot 2020-10-11 120837](https://user-images.githubusercontent.com/19403905/95675856-8352db00-0bba-11eb-98f5-bb6e1b7ce9f7.png)

**Comment by gadric** [comment]
Problem solved. see https://github.com/thomasloven/lovelace-card-mod/issues/78#issuecomment-706706010_

**Comment by Mariusthvdb** [comment]
yeah I saw that, but it remains a mystery. I couldn't reproduce the error before that update, nor can I reproduce the effectiveness or your use of the `in_card: true`

seems something else is at work in your config, because that isn't an option of the cards you are using.
