### ISSUE TITLE
26 TypeError: 691 is not a function (near '...i...')

### ISSUE THREAD

**Issue by gadric** [Mariusthvdb/custom-ui#20]
Hi, 

Just realized these days that there are a couple of errors in my logs related to custom_ui: 

```Logger: frontend.js.latest.202010012
Source: components/system_log/__init__.py:193 
First occurred: 12:14:42 PM (4 occurrences) 
Last logged: 12:34:35 PM

http://192.168.xxx.xxx:8123/local/custom_ui/custom-ui.js?v=20201024:2088:26 TypeError: 691 is not a function (near '...i...')
http://192.168.xxx.xxx:8123/local/custom_ui/custom-ui.js?v=20201024:2088:26 TypeError: 824 is not a function (near '...i...')
http://192.168.xxx.xxx:8123/local/custom_ui/custom-ui.js?v=20201024:2088:26 TypeError: 834 is not a function (near '...i...')
http://192.168.xxx.xxx:8123/local/custom_ui/custom-ui.js?v=20201024:2088:26 TypeError: 992 is not a function (near '...i...') 
```

I already downloaded the newest version (20201024) today, but still getting this error.

**Comment by Mariusthvdb** [comment]
any idea what customization causes this? TypeErrors mostly come from unknown entities and are not an error from the custom-ui, but an indiction you should guard the customization template

**Comment by gadric** [comment]
Hmm, actually no ... do you have a suggestion can I can debug this effectively?

**Comment by Mariusthvdb** [comment]
as always, cut customizations in half, and see if the error persists. if not add again half of the rest of the other half, etc etc. If not, start with the other half ;-)

more intelligently: check if you have template entities that might not yet be initialized or get reloaded with the reload template entities service.

Also, when do these errors show up, on startup or continuously

**Comment by gadric** [comment]
With customization, do you mean also mean integrations or only the Lovelace custom cards? 

The error seems to pop up only at the start.

**Comment by Mariusthvdb** [comment]
only things you set under

```
homeassistant:
  customize:
```

or the `_glob` and `_domain` variant

**Comment by gadric** [comment]
This is really funny now ... I commented out everything on customize.yaml and the error was gone. Then I put back everything back again and the error is still gone ... I have no idea why the error is now gone with any changes ...

**Comment by gadric** [comment]
I am 100% sure yet, but I think I found the error: 

```
"*.*":
  custom_ui_state_card: state-card-custom-ui
```

I don't know why this peace of code was in my `customize_glob.yaml` but I removed it and everything seems to work and the error did not appeared until now.

**Comment by Mariusthvdb** [comment]
a yes, as always RTFM... :-)
