### ISSUE TITLE
Groups more-info shows all attributes

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-ui#22]
referencing https://github.com/Mariusthvdb/custom-ui/pull/21 and please allow the tag @CAB426 , I now notice the more-info on groups still show all attributes, even when hidden in the custom-ui.

Note sure if this is new, but could you check if this is happening in your setup too? If so, we have a new challenge ;-)

**Comment by Mariusthvdb** [comment]
you're fast!

afraid though, a bit too fast, because this brings back all hidden attributes  on other entities I quickly tested? Doesn't that happen on your side, a simple automation or boolean, sensor, anything really except for groups ;-)

**Comment by CAB426** [comment]
You are correct, although I didn't see it until I upgraded to 0.117.5.  It seems to have continued to work on 0.117.4.  Working through 0.117.5 right now.  Should have an update shortly.

**Comment by CAB426** [comment]
My fault, I committed code that was missing one update.  The if statement had a single "=" in the condition, not the correct "==".  I pushed the update.  Everything seems to be working now.  Must've been something stuck in cache when I was testing before.

**Comment by Mariusthvdb** [comment]
thanks to the efforts of @CAB426 thins now resolved, please update to version 20201111 !
