### ISSUE TITLE
HA 118 (beta) shows hidden attributes

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-ui#24]
and sometimes even the templates again:

<img width="412" alt="Schermafbeelding 2020-11-12 om 09 05 21" src="https://user-images.githubusercontent.com/33354141/98913626-e1c7ed80-24c7-11eb-9cb6-c9cc6e4674dc.png">
<img width="998" alt="Schermafbeelding 2020-11-12 om 09 09 15" src="https://user-images.githubusercontent.com/33354141/98913632-e2f91a80-24c7-11eb-95de-298c546d5e97.png">

seems to be different between browsers (quickly checked Chrome and Safari on the Mac) though all seem to show at least the attributes, including custom-ui 's on hide_attributes setting.

Need some further investigating.

**Comment by Mariusthvdb** [comment]
so 118 has landed, and showing the above issue now in Core relate HA. @CAB426 don you also see this? Can we mitigate this new behavior? Or is it here to stay because of the many changes in the core more-info logic.

**Comment by CAB426** [comment]
I created a PR for these changes.  Once again, changing the element structure on the more-info popup. PR #25
