### ISSUE TITLE
HA 2020.12.x shows hidden attributes yet again

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-ui#26]
Seems to be a repeating issue with the last few HA updates, but all hidden attributes are back again...
<img width="403" alt="Schermafbeelding 2020-12-03 om 15 05 58" src="https://user-images.githubusercontent.com/33354141/101029199-46331580-3579-11eb-8f8f-f800c896e6fb.png">

@CAB426 please if you find a spare moment, could you again have a look? release 1.0 is due for dec 13th, and it would be so cool if this would be fixed before the holidays ;-)

thanks in advance!

**Comment by skynet01** [comment]
yes please, will love you forever :)

**Comment by CAB426** [comment]
Sorry guys, I started a new job.  Been buried.  I tried upgrading tonight and it blew up my installation.  I'm back up and running but I won't be trying this again until after the holiday season.  Be back after the New Year.  Cheers!

**Comment by Mariusthvdb** [comment]
well, that's good news isn't it? Congrats on the new job! 
enjoy the year's End, and hope to hear back from you indeed.

**Comment by Mariusthvdb** [comment]
fixed in https://github.com/Mariusthvdb/custom-ui/releases/latest

made a quick addition to the more-info version checker. hope this will hold now.
