### ISSUE TITLE
Not seeing the customUI under developer Tools/info

### ISSUE THREAD

**Issue by farberm** [Mariusthvdb/custom-ui#3]
I am not sure that I placed the lovelace resource folder in the correct location.

I am running hass.io on my synology via docker.

I placed the lovelace folder under www (see image). Where should it be for my setup?
![Screen Shot 2020-06-08 at 5 34 45 PM](https://user-images.githubusercontent.com/16128857/84082744-5f824d00-a9ae-11ea-84be-b8795a5b7bab.png)

**Comment by Mariusthvdb** [comment]
How did you 'tell' Lovelace where to find the file?

**Comment by farberm** [comment]
Here is what is in my config.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  extra_module_url:
    - /local/lovelace/resources/custom-ui/custom-ui.js

I also went to Configuration-->Lovelace-->Resources and created a new resource with the orange plus button as the following

.local/lovelace/resources/custom-ui/custom-ui.js
<img width="1081" alt="Screen Shot 2020-06-09 at 7 43 56 AM" src="https://user-images.githubusercontent.com/16128857/84143727-102b3380-aa25-11ea-8154-2da684ce0da8.png">

**Comment by Mariusthvdb** [comment]
if you are using the frontend method, you should add `frontend`: in your configuration.yaml above the `extra_module_url:`, see
https://github.com/Mariusthvdb/custom-ui#using-frontend

**Comment by farberm** [comment]
I edited my config file as suggested but still do not see the customUI?
I even did three restarts?
Do I need to move it above the themes:... line?

 Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/lovelace/resources/custom-ui/custom-ui.js

**Comment by Mariusthvdb** [comment]
please format your code correctly so we can see if it is alright, using the <> in the menu bar above, or using 3 back ticks before and after the code
```
like this
```

**Comment by farberm** [comment]
`# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
  - /local/lovelace/resources/custom-ui/custom-ui.js
`
Here is a screenshot. Validated code check and also configuration check. I do not see the error any longer however, I still do not have custom UI under developer info??

![Screen Shot 2020-06-09 at 5 28 32 PM](https://user-images.githubusercontent.com/16128857/84203116-e4d13480-aa76-11ea-99dd-1b262189b668.png)

**Comment by farberm** [comment]
ok. I removed all the frowned references and installed via HACS. Now I see the custom UI. Thanks for you help.

Credit goes to walaj. Jon Waland

OR, as you have hacs installed,

HACS->FrontEnd, select the three dots/hamburger/right top menu button -> custom repositories
enter https://github.com/Mariusthvdb/custom-ui as a lovelace entry, click add

close the repositories window, and you should have a new CustomUI /New repository on the screen. Select install. wait a few seconds for it to download, and select install

Now select the main configuration side menu->LoveLace Dashboards->Resources
and make sure you have /hacsfiles/custom-ui/custom-ui.js listed.

IF you don’t, add it as a javascript module.

Refresh page
Select developer tools side menu item -> info.

make sure you have somethign like

Custom UIs:
JS 20200528-adapted-for-HA110+

**Comment by Mariusthvdb** [comment]
>  Validated code check and also configuration check. I do not see the error any longer

yes, that's correct, and after you made this correction, you should have restarted once more.

Or, as you did, do as is instructed in this repo, delete all references, and use one of the described methods. Or use HACS...

glad you got it working.
