### ISSUE TITLE
Customizing icon_color not working after page refresh

### ISSUE THREAD

**Issue by dmatora** [Mariusthvdb/custom-ui#30]
Am I only person experiencing this?

**Comment by Mariusthvdb** [comment]
Duplicate of https://github.com/Mariusthvdb/custom-ui/issues/29 ?

**Comment by dmatora** [comment]
Not really, I'm talking about entities that do have unique id

**Comment by dmatora** [comment]
This is before refresh
<img width="1515" alt="image" src="https://user-images.githubusercontent.com/647062/103358032-b4f68680-4ac5-11eb-93f1-8b801599e8a5.png">
This is after
<img width="1523" alt="image" src="https://user-images.githubusercontent.com/647062/103358024-ab6d1e80-4ac5-11eb-873b-9c84a5d8df27.png">

**Comment by Mariusthvdb** [comment]
please add all info on your system so we can start analyzing this.

also, provide minimum config for a failing entity you can reproduce.

**Comment by dmatora** [comment]
If you want I can let you connect to my computer using anyDesk so you can look around

**Comment by Mariusthvdb** [comment]
no thanks, please just do as I asked, provide a minimum failing config section, and your system info. Would be nice if you could show any errors you get in Inspector

**Comment by dmatora** [comment]
No errors in Inspector, herу is system info
## System Health

version | 2020.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 4.19.127-v7l
arch | armv7l
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4986
Installed Version | 1.9.0
Stage | running
Available Repositories | 703
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | HassOS 4.17
-- | --
update_channel | stable
supervisor_version | 2020.12.7
docker_version | 19.03.12
disk_total | 28.6 GB
disk_used | 7.4 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | Portainer (1.3.0), deCONZ (6.6.1), Terminal & SSH (8.10.0), Mosquitto broker (5.1), Zigbee2mqtt (1.16.2.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 6
-- | --
mode | auto-gen
resources | 1

</details>

**Comment by dmatora** [comment]
Here is minimum failing config section
```
sensor.pool_humidity_in:
  templates:
    icon_color: >
      if (state > 80) return 'rgb(249,105,111)';
      else if (state > 70) return 'rgb(251,196,118)';
      else if (state > 60) return 'rgb(245,229,59)';
      else if (state > 50) return 'rgb(68,196,158)';
      else if (state > 40) return 'rgb(129,165,210)';
      else if (state > 30) return 'rgb(68,196,158)';
      else if (state > 20) return 'rgb(245,229,59)';
      else if (state > 15) return 'rgb(251,196,118)';
      else return 'rgb(249,105,111)';
```

**Comment by ed-holland** [comment]
I've updated #29 . The refresh issue occurs using chrome native refresh. Just switching dashboards is not causing the problem.
Customizing works fine for the rest.

**Comment by dmatora** [comment]
Ok, closing as duplicate of #29
