### ISSUE TITLE
Icon color not updating despite following steps

### ISSUE THREAD

**Issue by backslashV** [Mariusthvdb/custom-ui#31]
Hi,
I have the following in my customize.yaml:
```
yahoofinance.qcom:
  friendly_name: QCOM
  templates:
    icon_color: >
      if is_state_attr('yahoofinance.qcom', 'trending', 'up') return 'green';
      return 'red';
```
However, the icon color does not change. Could you help?

**Comment by Mariusthvdb** [comment]
Is_state_atr() is Jinja, while you need a JS style template

**Comment by backslashV** [comment]
> Is_state_attr() is Jinja, while you need a JS style template

Thanks. Using `state` also doesn't work. The entity has a numerical state and I'm checking `if state == 156`

**Comment by Mariusthvdb** [comment]
that's another template?

**Comment by backslashV** [comment]
> > Using state also doesn't work. The entity has a numerical state and I'm checking if (state == 156)
> 
> that's another template?
> btw, the entity `yahoofinance.qcom` is correct? which integration created that? Are you sure it isnt a sensor, like `sensor.yahoofinance_qcom`?
> 
> If its not in the supported domains (`yahoofinance` in this example) I am afraid custom_ui wont work

It's an entity of its own from the yahoofinance integration. What are all the supported domains?

**Comment by Mariusthvdb** [comment]
please show the entity in the developer-tools/state with a screenshot?

supported domains are the core HA domains. And even then, some entities can't be customized with custom_ui, like entities created in Python scripts. 

Experimenting is always possible, so, if you have an entity with an odd domain (like the one you present now) one never knows ;-)

also, if templating on numbers, you need to be sure it is an actual number or in fact a string. In the latter case, you need to quote the number, or add a int or float filter to the state.

**Comment by Mariusthvdb** [comment]
btw, for testing purposes I installed the CC, and this works fine:

```
    yahoofinance.istnx:
      templates:
        icon_color: >
          if (attributes.trending == 'up') return 'green';
          return 'red';
```

so please let me know if you have further issues.

**Comment by backslashV** [comment]
Appreciate your quick response. Here is a screenshot of the entity
![image](https://user-images.githubusercontent.com/8752221/104261349-350fdb00-543a-11eb-887e-38f35929c5cb.png)

Here is what I have in customize.yaml:
![image](https://user-images.githubusercontent.com/8752221/104261421-5c66a800-543a-11eb-91a7-4f22f3c41b5e.png)

And here is how it looks in lovelace:
![image](https://user-images.githubusercontent.com/8752221/104261459-730cff00-543a-11eb-9081-0fd041aa1451.png)

**Comment by Mariusthvdb** [comment]
please show the entity in an entities card. Your card probably is a custom button card, which has its own rules for formatting and customizing.

you can check if custom_ui was installed correctly, by looking at the info page, or in Inspector. please show that info to be sure.

**Comment by backslashV** [comment]
Thanks. It doesn't show in the info page. I added it the "modern" way. Here they are:
![image](https://user-images.githubusercontent.com/8752221/104343572-efdac000-54b0-11eb-8025-702dc75d4a2c.png)


In the Resources tab:
![image](https://user-images.githubusercontent.com/8752221/104343640-08e37100-54b1-11eb-9d94-fc179b81ede2.png)


In file editor:
![image](https://user-images.githubusercontent.com/8752221/104343718-24e71280-54b1-11eb-9660-be9bd9673bb5.png)

Info page:
![image](https://user-images.githubusercontent.com/8752221/104343782-37614c00-54b1-11eb-975d-1b9076dd1289.png)

**Comment by Mariusthvdb** [comment]
Don't think you're showing a regular entities card there, it would look like my own post. Icon on the left. 

And of course, if it isn't displayed in the info page install wasn't successful.

Did you download the resource correctly?

**Comment by backslashV** [comment]
entities card is the same.
I downloaded the repo (on windows) and uploaded the js file and it complained about some syntax error. Then, I cloned the repo directly in HA terminal and put the .js file in the aforementioned dir.

**Comment by Mariusthvdb** [comment]
modern way:

browse to your instances config/lovelace/resources:

<img width="1526" alt="Schermafbeelding 2021-01-12 om 19 44 42" src="https://user-images.githubusercontent.com/33354141/104358434-ba64bf80-550e-11eb-856d-452e590a6c14.png">

file in /config/www/lovelace/resources/custom-ui/

<img width="999" alt="Schermafbeelding 2021-01-12 om 19 47 59" src="https://user-images.githubusercontent.com/33354141/104358695-1891a280-550f-11eb-92dc-873de41a2f8a.png">

**Comment by backslashV** [comment]
Thank you. It appears the directory must be created under `www/lovelace/resources`.
I did not have the lovelace dir. I put it under `www/custom-ui`. All is working now. Thanks a lot for your time.

**Comment by Mariusthvdb** [comment]
of course we need proof of that ;-)

glad you got it working!

**Comment by backslashV** [comment]
> > All is working now.
> 
> of course we need proof of that ;-)
> 
> glad you got it working!

Indeed :D 
![image](https://user-images.githubusercontent.com/8752221/104397510-d150e500-5501-11eb-97ed-b399cea7e7b2.png)
