### ISSUE TITLE
why icon_color does not work?

### ISSUE THREAD

**Issue by Javito68** [Mariusthvdb/custom-ui#35]
Greetings to all,
  I do not understand why this code to change the color It does not work, in : config/customize.yaml:

#Sensores Estacion Meterologica:
sensor.temperatura1:
  friendly_name: "Temperatura dht22"
  icon: mdi:speedometer-slow
  templates:
    #icon_color: green
    icon_color: >
      if (state < 25) return 'green';
      else return 'red';

 Target:
![image](https://user-images.githubusercontent.com/46301145/114206228-6cb7f180-995b-11eb-974d-94e61ed56c06.png)

Entity:
![image](https://user-images.githubusercontent.com/46301145/114206425-a12bad80-995b-11eb-8e47-2710e49b839d.png)
Config-> Info:
![image](https://user-images.githubusercontent.com/46301145/114206708-e51eb280-995b-11eb-884c-9d13375677e0.png)

![image](https://user-images.githubusercontent.com/46301145/114206791-fcf63680-995b-11eb-8c7e-5aec0371abcf.png)

observing the file structure I don't have the lovelace directory in www, is it normal? it is installed in docker.
Thanks for everything!!!

**Comment by Mariusthvdb** [comment]
Hi, as the screen shot shows, you haven't yet installed custom-ui.

Please check the documentation how to do that first.

**Comment by Javito68** [comment]
thanks for answering Mariusthvdb, I just installed custom-ui:
![image](https://user-images.githubusercontent.com/46301145/114220997-fae8a380-996c-11eb-9554-aec7abbde4b3.png)

but it does not work, any suggestions?

![image](https://user-images.githubusercontent.com/46301145/114221200-4c912e00-996d-11eb-963a-6ed4d60a6543.png)

Thanks!!!

**Comment by Mariusthvdb** [comment]
You didn't install the custom-ui in this repo, but the old and no longer working version...

Please delete this and check the docs once more.

After that show the info page with the version installed

**Comment by Javito68** [comment]
Hi Marius, instalado:
![image](https://user-images.githubusercontent.com/46301145/114263230-9d903900-99e4-11eb-9878-cc38bebcdf9a.png)

now I have the following doubts:
    - Why does it not work in the target entity and if in the target entities?
  
![image](https://user-images.githubusercontent.com/46301145/114263332-1d1e0800-99e5-11eb-95d5-8be93b1258ee.png)
![image](https://user-images.githubusercontent.com/46301145/114263370-5f474980-99e5-11eb-8717-7dde4aa2689b.png)

-How can I hide attributes? I have used hide_attributes in customize.yaml and it doesn't work:

sensor.temperatura1:
  hide_attributes:
  friendly_name: "Temperatura dht22"
  icon: mdi:speedometer-slow
  templates:
    #icon_color: green
    icon_color: >
      if (state < 25) return 'red';
      else return 'green';


![image](https://user-images.githubusercontent.com/46301145/114263549-76d30200-99e6-11eb-9d99-8217cea17ca8.png)


thank you for your patience!!!

**Comment by Mariusthvdb** [comment]
Hide_attributes:

You didn't configure what to hide ;-) check the docs and see eg templates and icon_color, or simply set all

Color:
Could be 2 things: not always necessary, but did you also restart?

If so, it could be you need to quote the number (because it could be a string), so try '25'

**Comment by Javito68** [comment]
Hi,
 Hide_attributes -> Ok

Color:
 in each change restart, the data is numeric as string does not work, overridden the else:
sensor.temperatura1:
  hide_attributes:
    - templates
  friendly_name: "Temperatura dht22"
  icon: mdi:coolant-temperature
  templates:
    #icon_color: green
    icon_color: >
      if (state < 0) return 'red';
      if (state < 20) return 'yellow';
      if (state < 30) return 'green';
      if (state < 50) return 'red';
      
it not work in the target entity, why?
![image](https://user-images.githubusercontent.com/46301145/114264704-ba306f00-99ec-11eb-917a-4c6414b50079.png)

Thanks!!!

**Comment by Mariusthvdb** [comment]
that card probably can't be customized by custom-ui, because it uses another way of displaying the icon.

you need the [card-mod](https://github.com/thomasloven/lovelace-card-mod) resource by Thomas Loven, check https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1396 by @ildar_gabdullin for many suggestions to do so.

**Comment by Javito68** [comment]
Thanks and greetings !!!

**Comment by Mariusthvdb** [comment]
you're most welcome ;-)
closing.
