### ISSUE TITLE
Per-entity theming does not affect top-of-the-page badges

### ISSUE THREAD

**Issue by LupoCri** [Mariusthvdb/custom-ui#36]
Hi.

I would like to report that doesn't work the per-entity theming of the top-of-the-page **badges** .

It is possible?

Tnx

core-2021.4.3
CustomUI JS 20210322-X

**Comment by Mariusthvdb** [comment]
no, and it has never been possible in Lovelace. As a matter of fact Ive taken out all that code in the latest bets and todays release.

You have to do theme Badges with Card-mod.
