### ISSUE TITLE
Color not working, again?

### ISSUE THREAD

**Issue by tristone-cz** [Mariusthvdb/custom-ui#41]
Hi.

I noticed today (and probably even in few past weeks) that custom-ui is not handling icon colors.
As far as I can consider the other params are working - eg. icons themselves or brightness.

I checked the steps from similar past ticket and more or less the config looks well except one thing.
I can see in inspector the custom-ui loaded but cannot see it at `/config/info page`

I do not nderstand what's wrong. Accordgin the documentation the `icon_color` shall work.
I am attaching all relevant screen shots.

Plus the section from `customize_glob.yaml` (I tried simple color even and the icon_color2 is jsut a storage for values before elaborating with other ways):
```
    binary_sensor.*_contact*:
      templates:
        color: if (state == "off") return 'green'; return 'red';
        icon_color: if (state == "off") return 'green'; return 'red';
        icon_color2: if (state == "off") return 'rgb(53, 130, 181)'; return 'rgb(234, 175, 37)';
        brightness:  if (state == "off") return 71; return 92;
        icon: >
          if (state == "off") return "mdi:door-closed";
          return "mdi:door-open";
```

![resoruces](https://user-images.githubusercontent.com/40542489/121773625-66bdd700-cb7d-11eb-83d7-3dd20118c68c.png)

![inspector](https://user-images.githubusercontent.com/40542489/121773624-66bdd700-cb7d-11eb-968b-738fe510d223.png)

![info](https://user-images.githubusercontent.com/40542489/121773623-66254080-cb7d-11eb-9364-5da4da7f4774.png)

![card](https://user-images.githubusercontent.com/40542489/121773622-658caa00-cb7d-11eb-8aec-1bf890c68385.png)

**Comment by Mariusthvdb** [comment]
No issues here and it should show in config/info. Maybe cache. Try reload a few times?

Btw, only use icon_color: templates 

![image](https://user-images.githubusercontent.com/33354141/121777910-ae9c2880-cb94-11eb-9c83-d8085043f9b9.jpeg)

**Comment by tristone-cz** [comment]
The more I investigate the more weird it is 😢 

Clearing cache does not help same as incognito mode.
But I foudn somethign - at first access to `config/info` I do not see the the Custom UIs. Then I have to got to the main dashboard, then back to `config/info` and for this second attempt I can see the CustomUIs.

But even so the color is not taken into account. And waht is more weird I realized that for all other colors specified the same way it works fine.

Eg. smoke works, contact does not (despite the format, single or multi line):
```
    binary_sensor.*smoke*:
      templates:
        icon_color: >
          if (state == "off") {
            return 'rgb(22, 200, 38)';
          } else {
            return 'rgb(255, 22, 38)';
          }
        icon: >
          if (state == "off") {
            return "mdi:smoking-off";
          } else {
            return "mdi:alarm-light";
          }
    binary_sensor.*_contact*:
      templates:
        icon_color: >
          if (state == "off") return 'rgb(53, 130, 181)';
          return 'rgb(234, 175, 37)';
        brightness2:  if (state == "off") return 71; return 92;
        icon: >
          if (state == "off") return "mdi:door-closed";
          return "mdi:door-open";
```


![image](https://user-images.githubusercontent.com/40542489/121779244-12c1eb00-cb9b-11eb-9126-4bdbf3043ff4.png)

**Comment by Mariusthvdb** [comment]
these are globs, did you put these under `customize_glob:` ?

also, sometimes changing these templates does take a restart, simply reloading customization doesnt always work

**Comment by tristone-cz** [comment]
Yes, all my setting are in `customize_glob`.

And I am doing restarts between attempts.

BUT - I found explanation why it works sometimes and sometimes not. But the why not case makes not much more sense than before.
If the entity is part of `glance` card or `entities` card the icon_color is propagated fine. But for the card I am using - type `button` - the color is not taken into account. It is standard lovelace card, no custom.
And for sure it worked before. Just not sure how long it is broken.

**Comment by Mariusthvdb** [comment]
not broken, it simply isnt used by all cards like it was before. You have to use card-mod for colorizing the cards in some these.
Glance works fine though

<img width="372" alt="Schermafbeelding 2021-06-12 om 17 26 40" src="https://user-images.githubusercontent.com/33354141/121781058-60425600-cba3-11eb-98d6-0f7932bffc6f.png">

**Comment by tristone-cz** [comment]
Well, broken from the perspective that it worked before 😄 

So I think it is clear now even if I am not much happy of that.

Trying to play with card-mod which is far less comportable - not possible to do it once in global 😢

**Comment by Mariusthvdb** [comment]
yep, the global thing is what's keeping me in custom-ui. though you can set some of these in themes using card-mod too.
really suggesting you should have a look at that. this is a very active thread on the community https://community.home-assistant.io/t/card-mod-super-charge-your-themes/212176

**Comment by tristone-cz** [comment]
Thanks for hints 👍 

I managed the situation so far by changing button card to glance card. And making icons bigger with card-mod. 
Templating color for button card via card-mod I did not succeded.

Let's see how long glances will remain working 🤔

**Comment by Mariusthvdb** [comment]
Use custom button-card and set colors using templates natively.

I've even got a button-card template to make the buttons read the custom-ui templates ... (-)

**Comment by tristone-cz** [comment]
Wow. 
I am using at one place that card but was not aware it is so powerfull. It probably evolved since I discover it first.

Even templating is not needed. There is option to handle styles directly based on state value. Eg.:
```
type: custom:button-card
state:
  - value: 'on'
    styles:
      icon:
        - color: red
```

Thanks man.

**Comment by Mariusthvdb** [comment]
Yep. Romrider (custom button-card) and Thomas (card-mod an a lot more) are the best !
