### ISSUE TITLE
why this templates can not work?

### ISSUE THREAD

**Issue by DavidGtb** [Mariusthvdb/custom-ui#43]
homeassistant:
  customize: 
    person.david:
      templates:
        state: >
          {% if is_state("sensor.david_iphone11", "home") and is_state("device_tracker.david_iphone11", "home") %}
            home
          {% else %}
            not_home
          {% endif %};

i want change person.david state by sensor.david_iphone11 and device_tracker.david_iphone11 .but dosent work.

it is works well in developer-tools/template

**Comment by Mariusthvdb** [comment]
Yes, and that is the exact reason it doesn't work in custom-ui...

Please read the docs first.

O and btw, templating state isn't a good idea. Better create a template sensor for that

**Comment by DavidGtb** [comment]
i changed like this:
    person.david:
      templates:
        state: >
          if (entities['sensor.david'].state == 'home') return 'home';
          return 'not_home';
        entity_picture: >
          if (entities['sensor.david'].state == 'home') return '/local/people/david_home.jpg';
          return '/local/people/david_not_home.jpg';

i'd like use  templating state to defined the person's state. beacause person.user works well than sensor.user in badge model.

**Comment by Mariusthvdb** [comment]
closing, if needed please create a new issue.
