### ISSUE TITLE
custom-ui.js:219:9 Uncaught TypeError: Cannot read properties of undefined (reading 'state')

### ISSUE THREAD

**Issue by danielbrunt57** [Mariusthvdb/custom-ui#45]
Logger: frontend.js.latest.202112150
Source: components/system_log/__init__.py:189
First occurred: 4:54:17 PM (537 occurrences)
Last logged: 4:54:49 PM

https://brunt.duckdns.org/hacsfiles/custom-ui/custom-ui.js:219:9 Uncaught TypeError: Cannot read properties of undefined (reading 'state')

**Comment by Mariusthvdb** [comment]
And the issue is?

**Comment by danielbrunt57** [comment]
I don't know!  custom-ui seems to be working but this error occurs at startup and I don't know why...

**Comment by Mariusthvdb** [comment]
what did you add or change? are you new to custom-ui? did you add a template. please provide some basic info....

this happens when a 'state' in an entity isnt yet available, and the template you made isnt guarding that

**Comment by danielbrunt57** [comment]
I am not new to custom-ui... probably 8 months or more?  I'll dig deeper, review my templates and try and narrow it down, thanks,

**Comment by Mariusthvdb** [comment]
only asking because if it suddenly errors, it must a new template you added

**Comment by danielbrunt57** [comment]
I have not made any template changes recently,  I know you are in the dark as far as my setup so I will delve further.  I do remote IT support so I know how frustrating it can can be trying to determine what might be the problem!  I will investigate., thanks!

**Comment by Mariusthvdb** [comment]
Np, glad to help.

If you didn't change your templates, maybe you changed the affected entities ;-)

All I can tell you is that custom-ui behaves as well as can be, even on latest 2022.1 dev. ( always trying to be ahead of things...)

So must be some change in your config.

**Comment by danielbrunt57** [comment]
It only occurs once when I restart HA so something is not available when custom-ui initializes,  What IT is is is unknown...  The error has been there for some time, how long is unknown right now.  Since everything SEEMS to be working as intended, I will "let sleeping horses lie"...

**Comment by Mariusthvdb** [comment]
ok, well, do as you like, but I would advise against that. It can lead to a non responding instance because of huge amounts of frontend errors. This time it might not be a 'bad' issue, but please be warned it can cause nasty issues.
