### ISSUE TITLE
net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by Hellis81** [Mariusthvdb/custom-ui#46]
I get an error that the custom_ui is not found:
![image](https://user-images.githubusercontent.com/61010215/148202192-ed151504-bbc8-40a4-b12e-4dbe7788a4b6.png)

The file is there:

![image](https://user-images.githubusercontent.com/61010215/148202304-200effcc-d7fe-42a2-8cbf-10a18523223a.png)

I appended the url with todays date to make sure it loads it new. 
I have tried to CTRL + F5.

What else is there to do?

Everything seems to work as it should. The icons are colored dynamically as I have coded in customize.yaml

**Comment by spockster1985** [comment]
You have the wrong path specified. Try changing it to /local/custom-ui/custom-ui.js
