### ISSUE TITLE
Uncaught TypeError: e.push is not a function

### ISSUE THREAD

**Issue by ovid-io** [Mariusthvdb/custom-ui#6]
I've seen this is a known error mentioned in the readme

I'm not sure how this version was built, but think a fix for the e.push error is to remove this block from the original project
https://github.com/andrey-git/home-assistant-custom-ui/blob/master/src/utils/hooks.js#L321

**Comment by Mariusthvdb** [comment]
thanks. The files on this repo aren't  'built', merely copied from the original and final files on Andrey s repo. So I am afraid we can only edit the custom_ui.js as available on this repo here, as long as no other build is created.

If you could/would have a go at the currently available files and test, that would be most welcome! It is a nasty error in the inspector, though harmless.

**Comment by vMeph** [comment]
is there a fix to wont show this error?

**Comment by Mariusthvdb** [comment]
as explained in the read-me: no there isn't (yet). PR 's are welcome!
