### ISSUE TITLE
icon changes defined in customize_glob stopped working on HA 2022.4

### ISSUE THREAD

**Issue by s0ftice** [Mariusthvdb/custom-ui#60]
Since I upgraded HA to 2022.4 (supervised), icon changes based on states stopped working for me.

The following code (defined in customize_glob.yaml) used to work fine with HA pre-2022.4:

```
"binary_sensor.rain01":
  templates:
    icon: >-
      if (state === 'on') return 'mdi:white-balance-sunny';
      return 'mdi:weather-rainy';
    icon_color: >-
      if (state === 'on') return 'rgb(253,216,54)';
      return 'rgb(68,115,158)';
```

**Expected (pre-2022.4 without page refresh):**
<img width="253" alt="Screenshot 2022-04-22 at 09 22 44" src="https://user-images.githubusercontent.com/44747731/164578362-21b842b5-f85c-416e-8f5a-3e50914f341b.png"> :arrow_right: <img width="252" alt="Screenshot 2022-04-22 at 09 23 40" src="https://user-images.githubusercontent.com/44747731/164578401-5673552d-de88-414b-bc47-3d0dc4e3705a.png">

**Current behaviour:**
<img width="253" alt="Screenshot 2022-04-22 at 09 22 44" src="https://user-images.githubusercontent.com/44747731/164578362-21b842b5-f85c-416e-8f5a-3e50914f341b.png"> :arrow_right: <img width="250" alt="Screenshot 2022-04-22 at 09 23 29" src="https://user-images.githubusercontent.com/44747731/164578418-1e915720-d04e-497b-ba08-06d14938c1a0.png">

As you can see, icon_color changes work fine (as in dynamically and without page refresh), but icon changes still require a page refresh to update.

By the way, I am not redefining states, I simply change the label of a custom:button-card based on on/off to display dry/wet.

I upgraded custom_ui to 20220419 and restarted HA (2022.4.6), still does not work.

Did I miss something?

Thanks,
softice

**Comment by fn87** [comment]
I had the same issue. Had to remove custom ui, clear cache and reinstall to make it work. No idea why I had to remove but now both colour and states change.

**Comment by s0ftice** [comment]
Yep, that helped! :)
thanks @fn87

**Comment by Mariusthvdb** [comment]
couvld you please post the yaml for the button card?

Asking, because custom:button-card isn't supposed to follow an icon_color in custom-ui at all, so I am rather surprised this is working in the first place.

Are you sure the card isnt simply following the themes default for on/off colors (paper-icon-color/paper-icon-active-color)?
maybe you have set the same colors in the theme?


As a matter of fact, I have a special card_mod template to follow custom-ui, and I dont think you use that here?

Otoh, an icon should be followed, (and I am glad it does work for you now)

**Comment by s0ftice** [comment]
No, I'm note sure. It might really just be the default color it's following - yes, I set the exact same color as the theme. I also use standard entities cards showing this sensor as well as other globally (icon and icon_color) customized entities.
So no, I'm not using your card_mod template.

Nevertheless, here the code of my button-card:

```
square: false
type: custom:button-card
entity: binary_sensor.rain01
name: Rain Detector
show_label: true
styles:
  icon:
    - padding-bottom: 10px
  label:
    - font-size: 13px
    - color: gray
    - padding-top: 5px
    - padding-bottom: 10px
label: |
  [[[
    if (states["binary_sensor.rain01"].state == 'off') return 'wet';
    else return 'dry';
  ]]]
```

Thanks for all your great work and participation in the community by the way!!!

**Comment by Mariusthvdb** [comment]
ok, in that case, my suspicion was correct ;-)

it would be my advise anyway, to use built-in Lovelace options as much as possible. So yes, set a color scheme in your theme, and use `state_color: true`  in cards, and on individual entities as much as possible. Try to minimize the custom-ui need as much as possible. Even I do that ;-)

using these colors myself for eg alert schemes, for which I dont want to use the regular on/off colors.

like:
```
    binary_sensor.*_alert:
      <<: *hide
      templates:
        icon_color: >
          return (state === 'on') ? 'var(--alert-color)' : 'var(--primary-color)';
```
hint for the label in your card:

```
  [[[
    return (entity.state === 'off') ?  'wet' : 'dry' ;
  ]]]

**Comment by s0ftice** [comment]
Thanks for the advice, and to be honest, I can't remember why I set the color there. Thinking about it, default color should have worked everywhere (I always use `state_color: true` anyways). Probably because I set 5 different colors for battery percentages, I must have thought I need to do it for other entities too :D

Will clean up my code now! Thanks again.
