### ISSUE TITLE
custom-ui causing issues in /Settings menu?

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-ui#65]
see:
https://community.home-assistant.io/t/2022-9-home-assistant-birthday-release/458283/177?u=mariusthvdb

<img width="440" alt="Schermafbeelding 2022-09-09 om 10 56 56" src="https://user-images.githubusercontent.com/33354141/189318576-6c9c1500-d836-4394-a47e-616c3cc047d5.png">

![Sep-09-2022 10-36-50](https://user-images.githubusercontent.com/33354141/189318581-235cc4a6-01d4-492d-93da-f24a4aaf5c04.gif)

added to the [more-info issue](https://github.com/Mariusthvdb/custom-ui/issues/64), this is a new step in the HA development where Custom-ui needs to be adapted thoroughly

please assist if you know your way around HA frontend and JS

**Comment by bratanon** [comment]
Seems to work for me.

![image](https://user-images.githubusercontent.com/812265/189353159-d23d61dd-1cb7-4e7f-a540-362bb08125b0.png)

**Comment by Mariusthvdb** [comment]
maybe it depends on the amount of customization going on in the background, on. constantly changing states.
I'll check that some more

**Comment by Mariusthvdb** [comment]
not exactly sure what fixed it, but using the latest  (pre-release GPT) version, and now on 2023.1 (beta), this behavior is now gone, so closing this
