### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-ui#87]
Failed to load resource: the server responded with a status of 404 (Not Found)

Deleted the plugin and reinstall, did not help.

http://x.x.x.x:8123/hacsfiles/custom-ui/custom-ui.js?hacstag=26755814820230106 net::ERR_ABORTED 404 (Not Found)

_Originally posted by @kristianolofsson in https://github.com/Mariusthvdb/custom-ui/issues/86#issuecomment-1377494439_

**Comment by Mariusthvdb** [comment]
can you see any resources there (please post a screenshot of the inspector panel so to help other users too)

just to test, and be sure the custom-ui resource itself is ok, please download it manually, and see if that brings back the functionality

**Comment by kristianolofsson** [comment]
<img width="1135" alt="Screenshot 2023-01-10 at 17 10 33" src="https://user-images.githubusercontent.com/7191232/211604884-becdb38d-bc41-49e6-be10-ef5444284d10.png">

Added the plugin manually and restarted HA. Can't see its getting loaded.

**Comment by Krocko** [comment]
I had the same.
Problem is that hacs is downloading the `custom-ui-gpt` file, but under the resources the name is still `custom-ui`

**Comment by kristianolofsson** [comment]
@Krocko ok! So how to solve it?

**Comment by Krocko** [comment]
@kristianolofsson rename the resource url

![image](https://user-images.githubusercontent.com/29394115/211636111-09fe3d51-26e4-4192-98e1-8e41b7d52813.jpeg)

**Comment by Mariusthvdb** [comment]
well, yes you could do that. But renaming is does not change the file obviously..

Its odd that HACS would do that, since I marked it a pre-release, and have explicitly Not changed the custom-ui file yet.

Iow, downloading custom-ui through HACS should still result in that file, and not the GPT file.

A better temporary solution would be to install the file manually, as I showed earlier and is documented in the repo. Simply change 1 line in the resources in your configuration, and point to the correct file name/folder.

Ofc, you can also download the pre-release and test it, like I have been doing, and confirm it works without flaw. So I can next truly release that.

thanks for your find!

**Comment by Mariusthvdb** [comment]
so is this now resolved? in that case we can close.

**Comment by GSzabados** [comment]
> [?hacstag=26755814820230106](http://x.x.x.x:8123/hacsfiles/custom-ui/custom-ui.js?hacstag=26755814820230106)

I just ran into the same problem with version 20230106. And by manually removing the ?hacstag=..... part solves the issue. I really don't understand why it causes the 404 error with the ?hacstag for custom-ui.js and not for anything else.
