### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by sephrioth** [Mariusthvdb/custom-ui#88]
### Describe the issue

After upgrade to HA 2023.02, this error flooded my log and won't stop.

http://xxxx:8123/hacsfiles/custom-ui/custom-ui.js?hacstag=26755814820221115:206:14 TypeError: undefined is not an object (evaluating 'entities['sensor.crypto_btc_24hours_change'].state')

I tried :
- disable this particular entity
- remove custom-ui

But still no lucky. Then I [opened an issue ](https://github.com/hacs/integration/issues/3050)on HACS repo, but they said it's not their prob.

<div class="mdc-dialog__container" style="display: flex; flex-direction: row; align-items: var(--vertical-align-dialog, center); justify-content: space-around; box-sizing: border-box; height: 1136px; transform: none; opacity: 1; pointer-events: none; color: rgba(0, 0, 0, 0.6); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="mdc-dialog__surface" style="box-shadow: var(--mdc-dialog-box-shadow, 0px 11px 15px -7px rgba(0, 0, 0, 0.2), 0px 24px 38px 3px rgba(0, 0, 0, 0.14), 0px 9px 46px 8px rgba(0, 0, 0, 0.12)); position: var(--dialog-surface-position, relative); display: flex; flex-direction: column; flex-grow: 0; flex-shrink: 0; box-sizing: border-box; max-width: var(--mdc-dialog-max-width, 560px); max-height: var(--mdc-dialog-max-height, calc(100% - 32px)); pointer-events: auto; overflow-y: auto; background-color: var(--mdc-theme-surface, #fff); border-radius: var(--ha-dialog-border-radius, 28px); min-width: var(--mdc-dialog-min-width, 280px); top: var(--dialog-surface-top); margin-top: var(--dialog-surface-margin-top); min-height: var(--mdc-dialog-min-height, auto);"><h2 id="title" class="mdc-dialog__title" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-headline6-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-headline6-font-size, 1.25rem); line-height: var(--mdc-typography-headline6-line-height, 2rem); font-weight: var(--mdc-typography-headline6-font-weight, 500); letter-spacing: var(--mdc-typography-headline6-letter-spacing, 0.0125em); text-decoration: var(--mdc-typography-headline6-text-decoration, inherit); text-transform: var(--mdc-typography-headline6-text-transform, inherit); display: block; position: relative; flex-shrink: 0; box-sizing: border-box; margin: 0px 0px 1px; padding: 24px 24px 0px; color: var(--mdc-dialog-heading-ink-color, rgba(0, 0, 0, 0.87));"><div class="header_title" style="margin-right: 32px; margin-inline-end: 32px; margin-inline-start: initial; direction: var(--direction);">System information</div><ha-icon-button dialogaction="close" class="header_button" style="display: inline-block; outline: none; position: absolute; right: 16px; top: 14px; text-decoration: none; color: inherit; inset-inline-start: initial; inset-inline-end: 16px; direction: var(--direction);"><mwc-icon-button title="Close" style="display: inline-block; outline: none; --mdc-ripple-color: currentcolor; -webkit-tap-highlight-color: transparent; vertical-align: top; --mdc-theme-on-primary: currentColor; --mdc-theme-text-disabled-on-light: var(--disabled-text-color);"><button class="mdc-icon-button mdc-icon-button--display-flex" aria-label="Close" style="font-size: 24px; width: var(--mdc-icon-button-size, 48px); height: var(--mdc-icon-button-size, 48px); padding: calc( (var(--mdc-icon-button-size, 48px) - var(--mdc-icon-size, 24px)) / 2 ); display: inline-flex; position: relative; box-sizing: border-box; border: none; outline: none; background-color: transparent; fill: currentcolor; color: inherit; text-decoration: none; cursor: pointer; user-select: none; z-index: 0; overflow: visible; align-items: center; justify-content: center; vertical-align: top;"><span><slot><ha-svg-icon style="display: block; align-items: center; justify-content: center; position: relative; vertical-align: middle; fill: currentcolor; width: var(--mdc-icon-size, 24px); height: var(--mdc-icon-size, 24px);"><svg preserveAspectRatio="xMidYMid meet" focusable="false" role="img" aria-hidden="true" viewBox="0 0 24 24"><g><path d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></g></svg></ha-svg-icon></slot></span></button></mwc-icon-button></ha-icon-button></h2><div id="content" class="mdc-dialog__content" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-body1-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-body1-font-size, 1rem); line-height: var(--mdc-typography-body1-line-height, 1.5rem); font-weight: var(--mdc-typography-body1-font-weight, 400); letter-spacing: var(--mdc-typography-body1-letter-spacing, 0.03125em); text-decoration: var(--mdc-typography-body1-text-decoration, inherit); text-transform: var(--mdc-typography-body1-text-transform, inherit); flex-grow: 1; box-sizing: border-box; margin: 0px; overflow: auto; color: var(--mdc-dialog-content-ink-color, rgba(0, 0, 0, 0.6)); padding: var(--dialog-content-padding, 24px); position: var(--dialog-content-position, relative);"><slot id="contentSlot" style="margin-top: 0px; margin-bottom: 0px;"><div><div>

Version | core-2023.2.0
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.7
Operating System Family | Linux
Operating System Version | 4.4.59+
CPU Architecture | x86_64
Timezone | Asia/Shanghai
Configuration Directory | /config

</div></div></slot></div><footer id="actions" class=" mdc-dialog__actions " style="display: flex; position: relative; flex-shrink: 0; flex-wrap: wrap; align-items: center; justify-content: var(--justify-action-buttons, flex-end); box-sizing: border-box; min-height: 52px; margin: 0px; padding: 0px 24px 24px; border-top: 1px solid transparent;"><span style="flex: var(--secondary-action-button-flex, unset);"><slot name="secondaryAction"></slot></span><span style="flex: var(--primary-action-button-flex, unset);"><slot name="primaryAction"><mwc-button slot="primaryAction" style="display: inline-flex; outline: none; -webkit-tap-highlight-color: transparent; vertical-align: top; margin-left: 8px; margin-right: 0px; max-width: 100%; text-align: right;"><button id="button" class="mdc-button   " aria-label="Copy" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-button-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-button-font-size, 0.875rem); line-height: inherit; font-weight: var(--mdc-typography-button-font-weight, 500); letter-spacing: var(--mdc-typography-button-letter-spacing, 0.0892857em); text-decoration: var(--mdc-typography-button-text-decoration, none); text-transform: var(--mdc-typography-button-text-transform, uppercase); position: relative; display: inline-flex; align-items: center; justify-content: center; box-sizing: border-box; min-width: 64px; border: none; outline: none; user-select: none; appearance: none; overflow: hidden; vertical-align: middle; background: transparent; padding-top: 0px; padding-right: var(--mdc-button-horizontal-padding, 8px); padding-bottom: 0px; padding-left: var(--mdc-button-horizontal-padding, 8px); height: 36px; border-radius: var(--mdc-shape-small, 4px); flex: 1 1 auto; color: var(--mdc-theme-primary, #6200ee);"><span class="leading-icon"><slot name="icon"></slot></span><span class="mdc-button__label" style="position: relative;">COPY</span><span class="slot-container   " style="display: inline-flex; align-items: center; justify-content: center;"><slot></slot></span><span class="trailing-icon"><slot name="trailingIcon"></slot></span></button></mwc-button></slot></span></footer></div></div><br class="Apple-interchange-newline">

**Comment by Mariusthvdb** [comment]
taking out the entity completely does not resolve the issue?
did you also comment the customization?

if you have an entity that might take some time to initialize, you should 'guard' the customization, so it does not kill your frontend trying to find it an set customizations to it, while not there.

Cant say that is happening here.

first comment the customization and see if the fixes this particular entity .

**Comment by sephrioth** [comment]
> taking out the entity completely does not resolve the issue? did you also comment the customization?
> 
> if you have an entity that might take some time to initialize, you should 'guard' the customization, so it does not kill your frontend trying to find it and set customizations to it, while not there.
> 
> Can't say that is happening here.
> 
> first comment the customization and see if the fixes this particular entity .

No, taking out doesn't solve the issue.
Just comment the customization, it still exists.

This entity is working good, state is correct.

Is there any cache or something like this?

**Comment by Mariusthvdb** [comment]
well, if you commented the customization (and cleared cache and indeed reloaded customizations) it can no longer be there.

if the system still errors on a configuration that is no longer in your configuration.... it must be a cache thing yes.

to be sure: this is only logged on that particular entity? (if you comment that customization, the logging remains the same?)

**Comment by sephrioth** [comment]
How can I clear the HACS(or something else) cache? I use docker and I reset the container before startup.
Yes, this is the only particular entity which reports error.

**Comment by Mariusthvdb** [comment]
you should not need to interfere with HACS, unless you want to completely disable a custom card.

changing customizations only require reloading the customizations Yaml tools section. maybe a browser refresh or 2. and a state change on the entity, because otherwise it wont re-evaluate that customization. You can do that in the dev tools/states

but first we need your customization to see if thats ok

**Comment by sephrioth** [comment]
sensor.crypto_btc_usd:
      icon: mdi:bitcoin 
      templates:
        icon_color: >
          if (entities['sensor.crypto_btc_24hours_change'].state < 0) return '#FF503C';
          if (entities['sensor.crypto_btc_24hours_change'].state > 0) return '#4ab956';

And I removed the icon_color part, and I see the color is grey(correct) on frontend.  
But the error is still popping up.

**Comment by Mariusthvdb** [comment]
ok, first off there is no 'else' in your template, always use that to be sure there is no template issue.

secondly, you use the state if another entity for the template. Which is fine, but you need to check if the other entity is available, see the example I posted above.

first check for existence, and if yes, continue, if not, use an extra else there.

if the error still pops up while you have set no customization, then you have anther problem.....

are you sure there is no there line of yaml containing `entities['sensor.crypto_btc_24hours_change'].state` anywhere?

**Comment by Mariusthvdb** [comment]
ok thanks.

I can not explain why using no customization on `sensor.crypto_btc_24hours_change` could render an error in the inspector like that. If you dint feed that customization to the system, it can not put the out. Unless it would indeed still be alive in the cache. Normally, clearing the cache inside your browser would fix that. A restart takes care of the also.

what if you use a different template just for testing.
just us something really verbose like
```
      templates:
        icon_color: >
          return (1 > 0) ? 'red' : 'green';
```

**Comment by sephrioth** [comment]
The color changed to red as expected, but the error continues...

**Comment by Mariusthvdb** [comment]
now that should be impossible.... if you don't have it in the customization anymore, and the new customization is in fact working. Proving the `sensor.crypto_btc_24hours_change` is no longer evaluated in the customization


unless you maybe have something set on that entity itself?

bte, you said it happened after updating to 2023.2 Could it be the integration creating the entity was changed.

because custom-ui has not been changed and is working without any error on this side's many test instances, and has been doing so during the full beta cycle.

**Comment by Mariusthvdb** [comment]
> even I removed custom-ui...

yep, also impossible.....
however:

you could run it manually, and not via HACS.

add it to your config (through editing `resources` if you use Yaml mode, or the UI Dashboard/resources if you use UI mode)

**Comment by sephrioth** [comment]
Yeah, it is really weird.  I just downgrade HA to 2023.01, no lucky.
Okay, I try to remove custom-ui again to see if there is any change.

**Comment by sephrioth** [comment]
Still here, I am going crazy...

**Comment by Mariusthvdb** [comment]
have you also deleted the files?

**Comment by sephrioth** [comment]
> have you also deleted the files?

Yes, I checked, no more custom-ui files.

**Comment by Mariusthvdb** [comment]
tbh, I am lost for ideas.
You have deleted all traces of the custom card, and yet you get an HACS error in the log. (btw edit your image above as it shows your server)

last idea: did you reload HACS too? somehow it seems to try and load the resource according to the original setup. Maybe stopping and restating HACS fixes it?

**Comment by sephrioth** [comment]
Thanks.. it's a local address.
I think restart the HA will reload the HACS, right?

**Comment by Mariusthvdb** [comment]
well, yes, but you can simply go to integrations and select the 3 dots menu and use Reload


<img width="487" alt="Scherm­afbeelding 2023-02-02 om 13 09 44" src="https://user-images.githubusercontent.com/33354141/216321039-9687a64a-22bd-49fe-a81c-391eb0ca7f1d.png">

**Comment by sephrioth** [comment]
Interesting, I didn't find HACS on my Device/Service page... it only on my side menu..

**Comment by Mariusthvdb** [comment]
not sure about that.... if your system can not find the HACS integration, it is bound to cause problems ....

maybe we're on to something here

**Comment by sephrioth** [comment]
I used to see it on that page, but I don't remember when it disappears...
Okay, I will do some test...

**Comment by sephrioth** [comment]
I just went into the container and run the HACS install command, then restart HA,  NO MORE ERRORS!!!
Now I am trying to redownload custom-ui and enable my configurations... finger across.

**Comment by Mariusthvdb** [comment]
just be sure it loads the correct version (there have been reports it ads the GPT version in the install string, whihc it shouldnt, as that is an experimental version)

**Comment by sephrioth** [comment]
Everything is okay now, thanks for you help and patient. @Mariusthvdb

**Comment by Mariusthvdb** [comment]
great!
closing ;-)
